### ISSUE TITLE
request issue

### ISSUE THREAD

**Issue by anujjhawar28** [mayank30/fdchain#17]
jab ammount wallet ammount se jyaada hota he tab bhi request jaa rahi he 
mera ye mana na he ki ye un necessary he 
##  udhar likha hone chahiye cant request due to more ammount to withdrwa then wallet ammount

agar money nahi he utne moeny  to request ku jaa rahi he ......
## aur humesha yaads rakhna jitna bhi ammount hoga request ka wo humesha hi wallet ki present ammount ke bara bar ya chota hoga 

NOTE :apn ko wallet me earning batani chahiye ki at present kitni he ..............
kuki ye wo earninge he jo change hoti rahegi transaction ke saath ...
koi send karega money koi withdraw karega 
## r8

aur han ek chiz aur agar mera paas 50/- he aur mene pahle withdraw request daali 20/- ki 
then mene apne ek friend ko 30/-pay or send kar diye ............
mere hisaab se ye posssible hona chahiye ..........
shayad tere hissaab se abhi ye he ki agar ek bhi request he aapki bank ke liye withdraw ki to aap kisiko kucch bhi send nahi kar sakte r8

**Comment by mayank30** [comment]
Bhai 

1) mere pass insufficent balance bata raha hai if wallet amt se zyaada paise daal diye toh 

2) Basic Flow is like 

a) User Can Transfer money with in wallets untill he doesnot have withdraw request 
b) if any withdraw request is there untill that processed, User can't transfer money. Because reason is 
hum process kheti hai --> as user request for withdrawal --> 
to paise ek dum se wallet se nahi kat te hai untill hum uske bank mein transfer nahi kar de .. 

To Suppose 
100 rs hai wallet balance hai 
u raise request 60 rs for withdraw but still ur wallet balance is 100 rs untill admin process money 60 Rs to ur bank account, woh hone ke baad .. balance kaam hogaa 

Once balance is become 40 /- then user can raise request and transfer money or ask for withdrawal
